name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # OSX takes 2x longer to build i.e. usually 8m instead of 4m for the linux/windows builds
        # maybe want to skip it for non-release builds. Alternatively maybe parallelize the osx targets
        # e.g. one VM can do buildMacosX64 buildMacosArm64 buildIosX64
        # and the other can do buildIosArm64 buildIosSimulatorArm64
        # or something like that
        os: [ ubuntu-latest, windows-latest ] #, macOS-latest
        include:
          - os: ubuntu-latest
            platform: linux
            build_command: build
#          - os: macOS-latest
#            platform: mac
#            build_command: build
          - os: windows-latest
            platform: windows
            build_command: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew ${{ matrix.build_command }} -Pplatform=${{ matrix.platform }} --stacktrace -Pnosign -PisCI
